PEN-2154: UI for invalid data
wapopartners/Fusion-Browser-Extension pull request #22
Opened 2022-03-28 12:03 UTC by beltrancaliz

[PEN-2154](https://arcpublishing.atlassian.net/browse/PEN-2154)

- Implemented a timeout check in the content script to verify the message event listener coming from Engine
- Component for displaying a message if no data/invalid data is received
- Edited styles on the refresh page

2022-03-28 15:18 UTC, JackHowa commented on src/components/Invalid.tsx
> +      The current page is either not a Fusion page, or it's using an
minor grammar/clarity suggestion:

The current page is not compatible with the Fusion Browser Extension. The extension requires a Fusion version of 3.3.0 or greater.

2022-03-28 15:20 UTC, JackHowa approved these changes
Working as expected! Nice work. 

Shows refresh to the page with the browser when moving away from the page. Off of the fusion master branch, I see the correct data. 

Had a minor grammar suggestion for clarity mostly.

2022-03-28 15:23 UTC, JackHowa commented on public/content.js
> +    console.log('Did not receive data')
I might hide this from the console as a suggestion. If a client is using the extension on another non-fusion page, I wouldn't want to add this info to their browser log. but not a huge deal

![Screen Shot 2022-03-28 at 10 22 43](https://user-images.githubusercontent.com/5950956/160432000-4846f10b-8843-401b-ad4c-7fc757cc5355.png)

2022-03-28 15:27 UTC, JackHowa commented on public/content.js
> +    console.log('Did not receive data')
saw this may have been deliberate but wasn't sure: `Implemented a timeout check in the content script to verify the message event listener coming from Engine`

2022-03-28 21:43 UTC, JackHowa requested changes
Noticing the log message on all of my pages, even when I don't open the extension 😿

2022-03-28 21:43 UTC, JackHowa commented on public/content.js
> +    console.log('Did not receive data')
yeah, actually, this log message has been appearing on all of my pages in the console, even when I don't open the extension window. Can this be removed? I think we'd want it to only happen on the extension being open as well

2022-03-29 11:37 UTC, beltrancaliz commented on public/content.js
> +    console.log('Did not receive data')
Yeah, this is mostly for us to know the reason no data was loaded since it's easier to debug. We can remove it once we do the official prod release

2022-03-30 10:59 UTC, merged